FROM rasa/rasa:3.6.18-full

WORKDIR /app

COPY ./rasa_chatbot /app

USER root
RUN pip install --upgrade pip && \
    pip install poetry==1.7.1 --no-cache-dir && \
    poetry config virtualenvs.create false && \
    poetry install --without dev --no-interaction


RUN rasa train

USER 1001

CMD ["run", "--enable-api", "--cors", "*"]
