services:
  rasa:
    build:
      context: ./retailGPT
      dockerfile: Dockerfile.rasa
    restart: unless-stopped

  actions:
    volumes:
      - ./retailGPT/datasets:/datasets:ro

    build:
      context: ./retailGPT
      dockerfile: Dockerfile.actions
    environment:
      - AZURE_OPENAI_API_KEY
      - AZURE_API_KEY
      - OPENAI_API_KEY
      - AZURE_LANGUAGE_KEY
    restart: unless-stopped

  demo:
    build:
      context: ./chat_interface
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: unless-stopped

  database:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
